fix custom-glibc

diff --git a/glibc-custom/glibc-2.36/debian/libc6.postinst b/glibc-custom/glibc-2.36/debian/libc6.postinst
--- a/glibc-custom/glibc-2.36/debian/libc6.postinst
+++ b/glibc-custom/glibc-2.36/debian/libc6.postinst
@@ -16,7 +16,28 @@ checkpkgver () {
 if [ "$type" = "configure" ]
 then
     # /etc/ld.so.nohwcap code:
-    __NOHWCAP__
+    # Handle upgrades when libc-opt package has been installed.
+    # When a /etc/ld.so.nohwcap file exists, ld.so only use libraries
+    # from /lib, and ignore all optimised libraries. This file is
+    # inconditionaly created in the preinst script of libc.
+ 
+    # We check the version between the current installed libc and
+    # all optimized packages. Due to multiarch, this has to be done
+    # independently of the architecture of the package.
+    all_upgraded=yes
+    for pkg in libc6.1-alphaev67 ; do
+        ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg[0-9a-z:]*\s\+//;s/\s.*//g")
+        if [ -n "$ver" ] && [ "$ver" != "CURRENT_VER" ]; then
+            all_upgraded=no
+        fi
+    done
+
+    # If the versions of all optimized packages are the same as the libc
+    # one, we could remove /etc/ld.so.nohwcap. Otherwise, it will be removed
+    # when all optimized packages are upgraded or removed.
+    if [ "$all_upgraded" = yes ] ; then
+        rm -f "$DPKG_ROOT/etc/ld.so.nohwcap"
+    fi
 fi
 
 if [ "$type" = configure ]
@@ -42,7 +63,37 @@ then
 	    check="$check wu-ftpd wu-ftpd-academ wwwoffle"
 	    check="$check webmin dropbear gdm"
 	    # NSS services check: 
-	    __NSS_CHECK__
+	    echo -n "Checking for services that may need to be restarted..."
+	    # Only get the ones that are installed, of the same architecture
+	    # as libc (or arch all) and configured. Restart openssh-server even
+	    # if only half-configured to continue accepting new connections
+	    # during the upgrade.
+	    check=$(dpkg-query -W -f='${binary:Package} ${Status} ${Architecture}\n' $check 2> /dev/null | \
+			grep -E "(^openssh-server .* unpacked|installed) (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
+	    # some init scripts don't match the package names
+	    check=$(echo $check | \
+		    sed -e's/\bapache2.2-common\b/apache2/g' \
+			-e's/\bat\b/atd/g' \
+			-e's/\bdovecot-common\b/dovecot/g' \
+			-e's/\bexim4-base\b/exim4/g' \
+			-e's/\blpr\b/lpd/g' \
+			-e's/\blpr-ppd\b/lpd-ppd/g' \
+			-e's/\bmysql-server\b/mysql/g' \
+			-e's/\bopenssh-server\b/ssh/g' \
+			-e's/\bsasl2-bin\b/saslauthd/g' \
+			-e's/\bsamba\b/smbd/g' \
+			-e's/\bpostgresql-common\b/postgresql/g' \
+		    )
+	    echo
+	    echo "Checking init scripts..."
+	    for service in $check; do
+		invoke-rc.d ${service} status >/dev/null 2>/dev/null && status=0 || status=$?
+		if [ "$status" = "0" ] || [ "$status" = "2" ] ; then
+		    services="$service $services"
+		elif [ "$status" = "100" ] ; then
+		    echo "WARNING: init script for $service not found."
+		fi
+	    done
 	    if [ -n "$services" ]; then
 
 	        if [ -f /usr/share/debconf/confmodule ] ; then
